version: '3.7'

services:
    # db:
    #     image: mysql:latest
    #     container_name: db
    #     restart: always
    #     environment:
    #         MYSQL_DATABASE: All_DB
    #         MYSQL_ROOT_PASSWORD: root
    #     ports:
    #         - 3306:3306

    all-backend:
        images: onionsss11/allinjob:1.0
        container_name: all-backend
        env_file:
            - .env.prod
        ports:
            - 4000:4000

    all-redis:
        image: redis:latest
        ports:
            - 6379:6379
