version: '3.7'

services:
    db:
        image: mysql:latest
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: All_DB
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    all-redis:
        image: redis:latest
        ports:
            - 6379:6379

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.0
        container_name: kibana
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200

    all-backend:
        build:
            context: .
            dockerfile: dockerfile
        container_name: all-backend
        volumes:
            - ./src:/backend/src
            - ./prisma:/backend/prisma
        depends_on:
            - db
            - elasticsearch
        environment:
            - ELASTICSEARCH_HOST=elasticsearch
            - HEALTHCHECK_URL=http://elasticsearch:9200/_cluster/health?wait_for_status=green&timeout=10s&level=shards%2Cindices&pretty=
            - HEALTHCHECK_INTERVAL=5s
        env_file:
            - .env
        ports:
            - 4000:4000

networks:
    default:
