version: '3.7'

services:
    all-backend:
        build:
            context: .
            dockerfile: dockerfile.prod
        container_name: all-backend
        env_file: .env
        ports: 4000:4000